kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /lib/modules
      containerPath: /mnt/lib/modules
    - hostPath: /sys/fs/bpf
      containerPath: /mnt/sys/fs/bpf
    - hostPath: /sys/kernel/debug
      containerPath: /mnt/sys/kernel/debug